export enum RecommendationType {
  RATE_LIMIT = 'RATE_LIMIT',
  WAF_RULE_REVIEW = 'WAF_RULE_REVIEW',
  WAF_RULE = 'WAF_RULE',
  AUTHENTICATION_POLICY = 'AUTHENTICATION_POLICY',
  IP_BLOCK = 'IP_BLOCK',
  SESSION_INVALIDATION = 'SESSION_INVALIDATION',
  MFA = 'MFA',
  API_PROTECTION = 'API_PROTECTION',
}
